-- Enes Doğanay | 6 Nisan 2026: Kurumsal basvuru, admin inceleme ve onay akisi icin gereken tablo tanimlari

create extension if not exists pgcrypto;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.kurumsal_basvurular (
  id bigint generated by default as identity primary key,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'needs_info')),
  applicant_first_name text not null,
  applicant_last_name text not null,
  applicant_title text,
  company_name text not null,
  listed_company_name text,
  website_url text,
  corporate_email text not null,
  phone text not null,
  tax_office text,
  tax_number text,
  company_address text,
  verification_note text,
  review_note text,
  reviewed_by_email text,
  approved_user_id uuid,
  managed_firma_id text,
  reviewed_at timestamptz,
  approved_at timestamptz,
  rejected_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.kurumsal_basvurular
  add column if not exists managed_firma_id text;

alter table public.kurumsal_basvurular
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create table if not exists public.kurumsal_firma_yoneticileri (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  firma_id text not null unique,
  application_id bigint unique references public.kurumsal_basvurular (id) on delete set null,
  role text not null default 'owner' check (role in ('owner', 'editor')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_epostalari (
  email text primary key,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_kurumsal_basvurular_pending_email
  on public.kurumsal_basvurular (lower(corporate_email))
  where status = 'pending';

create index if not exists idx_kurumsal_basvurular_status_created_at
  on public.kurumsal_basvurular (status, created_at desc);

create index if not exists idx_kurumsal_basvurular_company_name
  on public.kurumsal_basvurular (company_name);

create index if not exists idx_kurumsal_basvurular_managed_firma_id
  on public.kurumsal_basvurular (managed_firma_id);

create index if not exists idx_kurumsal_firma_yoneticileri_firma_id
  on public.kurumsal_firma_yoneticileri (firma_id);

drop trigger if exists set_kurumsal_basvurular_updated_at on public.kurumsal_basvurular;
create trigger set_kurumsal_basvurular_updated_at
before update on public.kurumsal_basvurular
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_kurumsal_firma_yoneticileri_updated_at on public.kurumsal_firma_yoneticileri;
create trigger set_kurumsal_firma_yoneticileri_updated_at
before update on public.kurumsal_firma_yoneticileri
for each row
execute function public.set_current_timestamp_updated_at();

alter table public.kurumsal_basvurular enable row level security;

alter table public.kurumsal_firma_yoneticileri enable row level security;

alter table public.admin_epostalari enable row level security;

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_epostalari
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.get_current_user_managed_firma_id()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select firma_id
  from public.kurumsal_firma_yoneticileri
  where user_id = auth.uid()
  order by id desc
  limit 1;
$$;

drop policy if exists "Anyone can submit corporate applications" on public.kurumsal_basvurular;
create policy "Anyone can submit corporate applications"
on public.kurumsal_basvurular
for insert
with check (true);

drop policy if exists "Admins can read corporate applications" on public.kurumsal_basvurular;
create policy "Admins can read corporate applications"
on public.kurumsal_basvurular
for select
using (public.is_current_user_admin());

drop policy if exists "Admins can update corporate applications" on public.kurumsal_basvurular;
create policy "Admins can update corporate applications"
on public.kurumsal_basvurular
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

drop policy if exists "Users can read own admin email row" on public.admin_epostalari;
create policy "Users can read own admin email row"
on public.admin_epostalari
for select
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "Users can read own managed company row" on public.kurumsal_firma_yoneticileri;
create policy "Users can read own managed company row"
on public.kurumsal_firma_yoneticileri
for select
using (auth.uid() = user_id or public.is_current_user_admin());

-- Enes Doğanay | 7 Nisan 2026: Kayit formlarinda e-posta musaitlik kontrolu icin RPC fonksiyonu
create or replace function public.check_email_availability(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_email text;
begin
  normalized_email := lower(trim(p_email));

  if exists (select 1 from auth.users where lower(email) = normalized_email) then
    return jsonb_build_object('available', false, 'reason', 'Bu e-posta adresi zaten kullanılmaktadır.');
  end if;

  if exists (select 1 from public.kurumsal_basvurular where lower(corporate_email) = normalized_email and status in ('pending', 'approved')) then
    return jsonb_build_object('available', false, 'reason', 'Bu e-posta adresi zaten kullanılmaktadır.');
  end if;

  return jsonb_build_object('available', true);
end;
$$;

-- Enes Doğanay | 6 Nisan 2026: Env yoksa admin tanimi icin kendi e-postanizi bir kez ekleyin
-- insert into public.admin_epostalari (email) values ('yonetici@ornek.com') on conflict (email) do nothing;
