-- Enes Doğanay | 4 Mayıs 2026: Firma ekip yönetimi migration
-- 1) kurumsal_firma_yoneticileri genişletme
-- 2) firma_davetleri tablosu
-- 3) RLS policies
-- 4) Helper fonksiyonlar

-- ═══════════════════════════════════════════════════════
-- 1) kurumsal_firma_yoneticileri GÜNCELLEMELERİ
-- ═══════════════════════════════════════════════════════

-- firma_id unique constraint kaldır — artık bir firmada birden fazla üye olabilir
-- user_id unique kalıyor — bir kullanıcı sadece bir firmada olabilir
ALTER TABLE public.kurumsal_firma_yoneticileri
  DROP CONSTRAINT IF EXISTS kurumsal_firma_yoneticileri_firma_id_key;

-- role check güncelle: owner | admin | member
ALTER TABLE public.kurumsal_firma_yoneticileri
  DROP CONSTRAINT IF EXISTS kurumsal_firma_yoneticileri_role_check;
ALTER TABLE public.kurumsal_firma_yoneticileri
  ADD CONSTRAINT kurumsal_firma_yoneticileri_role_check
  CHECK (role IN ('owner', 'admin', 'member'));

-- Unvan sütunu ekle (Satış Müdürü, CTO vb.)
ALTER TABLE public.kurumsal_firma_yoneticileri
  ADD COLUMN IF NOT EXISTS title text DEFAULT NULL;

-- Ekip sayfasında sıralama için
CREATE INDEX IF NOT EXISTS idx_kurumsal_firma_yoneticileri_firma_role
  ON public.kurumsal_firma_yoneticileri (firma_id, role);

-- ═══════════════════════════════════════════════════════
-- 2) firma_davetleri TABLOSU
-- ═══════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.firma_davetleri (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firma_id      text NOT NULL,
  invited_email text NOT NULL,
  invited_user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  invited_by    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role          text NOT NULL DEFAULT 'member'
                  CHECK (role IN ('admin', 'member')),
  title         text DEFAULT NULL,
  status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL DEFAULT (now() + interval '7 days')
);

-- Aynı firmaya aynı e-posta için sadece 1 bekleyen davet
CREATE UNIQUE INDEX IF NOT EXISTS idx_firma_davetleri_pending_unique
  ON public.firma_davetleri (firma_id, lower(invited_email))
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_firma_davetleri_firma_id
  ON public.firma_davetleri (firma_id);
CREATE INDEX IF NOT EXISTS idx_firma_davetleri_invited_user
  ON public.firma_davetleri (invited_user_id);
CREATE INDEX IF NOT EXISTS idx_firma_davetleri_invited_email
  ON public.firma_davetleri (lower(invited_email));

DROP TRIGGER IF EXISTS set_firma_davetleri_updated_at ON public.firma_davetleri;
CREATE TRIGGER set_firma_davetleri_updated_at
  BEFORE UPDATE ON public.firma_davetleri
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();

ALTER TABLE public.firma_davetleri ENABLE ROW LEVEL SECURITY;

-- ═══════════════════════════════════════════════════════
-- 3) firma_davetleri RLS POLİCY'LERİ
-- ═══════════════════════════════════════════════════════

-- Owner kendi firması için davet oluşturabilir
DROP POLICY IF EXISTS "firma_davetleri_owner_insert" ON public.firma_davetleri;
CREATE POLICY "firma_davetleri_owner_insert"
  ON public.firma_davetleri FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.kurumsal_firma_yoneticileri
      WHERE user_id = auth.uid()
        AND firma_id = firma_davetleri.firma_id
        AND role = 'owner'
    )
  );

-- Owner kendi firmasının davetlerini görebilir ve güncelleyebilir (iptal)
DROP POLICY IF EXISTS "firma_davetleri_owner_select" ON public.firma_davetleri;
CREATE POLICY "firma_davetleri_owner_select"
  ON public.firma_davetleri FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.kurumsal_firma_yoneticileri
      WHERE user_id = auth.uid()
        AND firma_id = firma_davetleri.firma_id
        AND role = 'owner'
    )
    OR invited_user_id = auth.uid()
  );

DROP POLICY IF EXISTS "firma_davetleri_owner_update" ON public.firma_davetleri;
CREATE POLICY "firma_davetleri_owner_update"
  ON public.firma_davetleri FOR UPDATE
  USING (
    -- Owner iptal edebilir
    EXISTS (
      SELECT 1 FROM public.kurumsal_firma_yoneticileri
      WHERE user_id = auth.uid()
        AND firma_id = firma_davetleri.firma_id
        AND role = 'owner'
    )
    -- Davet edilen kabul/ret edebilir
    OR invited_user_id = auth.uid()
  );

-- ═══════════════════════════════════════════════════════
-- 4) kurumsal_firma_yoneticileri YENİ RLS'LER
-- ═══════════════════════════════════════════════════════

-- Aynı firmadaki herkes birbirini görebilsin (ekip sayfası için)
-- NOT: Recursive olmaması için get_my_firma_id() SECURITY DEFINER fonksiyonu kullanılır
CREATE OR REPLACE FUNCTION public.get_my_firma_id()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT firma_id
  FROM public.kurumsal_firma_yoneticileri
  WHERE user_id = auth.uid()
  LIMIT 1;
$$;

DROP POLICY IF EXISTS "firma_yoneticileri_ekip_select" ON public.kurumsal_firma_yoneticileri;
CREATE POLICY "firma_yoneticileri_ekip_select"
  ON public.kurumsal_firma_yoneticileri FOR SELECT
  USING (
    auth.uid() = user_id
    OR firma_id = public.get_my_firma_id()
    OR public.is_current_user_admin()
  );

-- Owner yeni üye ekleyebilir (davet kabul akışında kullanılır)
DROP POLICY IF EXISTS "firma_yoneticileri_owner_insert" ON public.kurumsal_firma_yoneticileri;
CREATE POLICY "firma_yoneticileri_owner_insert"
  ON public.kurumsal_firma_yoneticileri FOR INSERT
  WITH CHECK (public.is_current_user_admin());

-- Owner üye rolünü/unvanını güncelleyebilir (kendi kaydı hariç)
DROP POLICY IF EXISTS "firma_yoneticileri_owner_update" ON public.kurumsal_firma_yoneticileri;
CREATE POLICY "firma_yoneticileri_owner_update"
  ON public.kurumsal_firma_yoneticileri FOR UPDATE
  USING (
    public.is_current_user_admin()
    -- Kullanıcı kendi unvanını güncelleyebilir
    OR auth.uid() = user_id
  );

-- Owner üyeyi silebilir (kendini silemesin)
DROP POLICY IF EXISTS "firma_yoneticileri_owner_delete" ON public.kurumsal_firma_yoneticileri;
CREATE POLICY "firma_yoneticileri_owner_delete"
  ON public.kurumsal_firma_yoneticileri FOR DELETE
  USING (
    public.is_current_user_admin()
    OR (
      auth.uid() != user_id
      AND EXISTS (
        SELECT 1 FROM public.kurumsal_firma_yoneticileri kfy2
        WHERE kfy2.user_id = auth.uid()
          AND kfy2.firma_id = kurumsal_firma_yoneticileri.firma_id
          AND kfy2.role = 'owner'
      )
    )
  );

-- ═══════════════════════════════════════════════════════
-- 5) HELPER FONKSİYONLAR
-- ═══════════════════════════════════════════════════════

-- Kullanıcının firmadaki rolünü döndürür (null = üye değil)
CREATE OR REPLACE FUNCTION public.get_user_firma_role(p_firma_id text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role
  FROM public.kurumsal_firma_yoneticileri
  WHERE user_id = auth.uid()
    AND firma_id = p_firma_id
  LIMIT 1;
$$;

-- Kullanıcı bu firmada en az belirtilen rolde mi?
-- owner > admin > member hiyerarşisi
CREATE OR REPLACE FUNCTION public.user_has_firma_role(p_firma_id text, p_min_role text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.kurumsal_firma_yoneticileri
    WHERE user_id = auth.uid()
      AND firma_id = p_firma_id
      AND CASE p_min_role
            WHEN 'member' THEN role IN ('owner', 'admin', 'member')
            WHEN 'admin'  THEN role IN ('owner', 'admin')
            WHEN 'owner'  THEN role = 'owner'
            ELSE false
          END
  );
$$;

-- Davet kabul edildiğinde kurumsal_firma_yoneticileri'ne ekle (SECURITY DEFINER)
CREATE OR REPLACE FUNCTION public.accept_firma_daveti(p_davet_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_davet record;
  v_existing_firma text;
BEGIN
  -- Daveti bul ve kilitle
  SELECT * INTO v_davet
  FROM public.firma_davetleri
  WHERE id = p_davet_id
    AND invited_user_id = auth.uid()
    AND status = 'pending'
    AND expires_at > now()
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', 'Davet bulunamadı veya süresi dolmuş.');
  END IF;

  -- Kullanıcı zaten başka bir firmada mı?
  SELECT firma_id INTO v_existing_firma
  FROM public.kurumsal_firma_yoneticileri
  WHERE user_id = auth.uid()
  LIMIT 1;

  IF v_existing_firma IS NOT NULL THEN
    RETURN jsonb_build_object('error', 'Zaten bir firmaya bağlısınız.');
  END IF;

  -- Firmaya ekle
  INSERT INTO public.kurumsal_firma_yoneticileri (user_id, firma_id, role, title, page_permissions)
  VALUES (auth.uid(), v_davet.firma_id, v_davet.role, v_davet.title,
    COALESCE(v_davet.page_permissions, '{"firma_paneli": false, "teklif_yonetimi": true, "ihale_yonetimi": true, "ekip_yonetimi": false}'::jsonb));

  -- Daveti kabul edildi olarak işaretle
  UPDATE public.firma_davetleri
  SET status = 'accepted', updated_at = now()
  WHERE id = p_davet_id;

  RETURN jsonb_build_object('success', true, 'firma_id', v_davet.firma_id, 'role', v_davet.role);
END;
$$;

-- ═══════════════════════════════════════════════════════
-- 6) PUBLİC EKİP BİLGİSİ VIEW (firma detay sayfası için)
-- ═══════════════════════════════════════════════════════
-- profiles tablosundaki first_name, last_name + role + title döndürür
-- Bu view herkese açık — FirmaDetay'da "Ekibimiz" bölümü için

DROP VIEW IF EXISTS public.firma_ekip_public;
CREATE VIEW public.firma_ekip_public AS
  SELECT
    kfy.user_id,
    kfy.firma_id,
    kfy.role,
    kfy.title,
    kfy.created_at AS joined_at,
    p.first_name,
    p.last_name,
    (coalesce(p.first_name, '') || ' ' || coalesce(p.last_name, ''))::text AS full_name,
    p.avatar AS avatar_url
  FROM public.kurumsal_firma_yoneticileri kfy
  JOIN public.profiles p ON p.id = kfy.user_id;

-- View için RLS bypass — sadece seçili kolonları döndürüyor, hassas veri yok
GRANT SELECT ON public.firma_ekip_public TO anon, authenticated;
