-- Enes Doğanay | 13 Mayıs 2026: Firma profil görüntüleme analitikleri
-- firmaID kaç kişi tarafından görüntülenmiş — anonim ve kayıtlı kullanıcılar

CREATE TABLE IF NOT EXISTS public.firma_goruntulemeler (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_id    text NOT NULL,            -- firmalar.firmaID (text uyumlu)
    viewer_id   uuid,                     -- NULL = anonim
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_firma_gorum_firma
    ON public.firma_goruntulemeler (firma_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_firma_gorum_viewer
    ON public.firma_goruntulemeler (viewer_id)
    WHERE viewer_id IS NOT NULL;

ALTER TABLE public.firma_goruntulemeler ENABLE ROW LEVEL SECURITY;

-- Herkes kayıt ekleyebilir (anonim izin)
CREATE POLICY "Görüntüleme kaydı ekle"
    ON public.firma_goruntulemeler FOR INSERT
    WITH CHECK (true);

-- Firma sahibi kendi görüntüleme sayısını okuyabilir
-- (service_role ile tüm kayıtlar okunabilir)
CREATE POLICY "Firma sahibi okur"
    ON public.firma_goruntulemeler FOR SELECT
    USING (
        viewer_id = auth.uid()
        OR EXISTS (
            SELECT 1 FROM public.kurumsal_firma_yoneticileri
            WHERE user_id = auth.uid()
              AND firma_id::text = firma_goruntulemeler.firma_id::text
        )
    );
