-- Enes Doğanay | 10 Nisan 2026: İhale teklifleri tablosu — kullanıcılar ihalelere teklif verir
-- Supabase Dashboard > SQL Editor'de bu dosyayı çalıştırın.

-- ═══════════════════════════════════════════════════════════════════════════
-- 1) TABLO
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.ihale_teklifleri (
    id                  bigint generated by default as identity primary key,
    ihale_id            bigint not null references public.firma_ihaleleri(id) on delete cascade,
    firma_id            text not null,                              -- ihalenin sahibi firma (firma_ihaleleri.firma_id)
    user_id             uuid not null references auth.users(id),    -- teklif veren kullanıcı
    gonderen_firma_id   text,                                       -- teklif verenin yönettiği firma id (varsa)
    gonderen_firma_adi  text,
    gonderen_ad_soyad   text not null,
    gonderen_email      text not null,
    kalemler            jsonb,               -- [{madde, aciklama, miktar, birim, birim_fiyat, not}]
    toplam_tutar        numeric(15,2) not null default 0,
    para_birimi         text not null default 'TRY' check (para_birimi in ('TRY','USD','EUR','GBP')),
    kdv_dahil           boolean not null default true,
    teslim_suresi_gun   integer,
    teslim_aciklamasi   text,
    not_field           text,                -- "not" reserved kelime olduğu için "_field" eki
    ek_dosya_url        text,
    ek_dosya_adi        text,
    durum               text not null default 'gonderildi'
                            check (durum in ('taslak','gonderildi','kabul','red')),
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);

-- updated_at otomatik güncellensin
drop trigger if exists ihale_teklifleri_updated_at on public.ihale_teklifleri;
create trigger ihale_teklifleri_updated_at
    before update on public.ihale_teklifleri
    for each row execute procedure public.set_updated_at();

-- İndeksler
create index if not exists idx_ihale_teklifleri_ihale on public.ihale_teklifleri (ihale_id);
create index if not exists idx_ihale_teklifleri_user on public.ihale_teklifleri (user_id);
create index if not exists idx_ihale_teklifleri_firma on public.ihale_teklifleri (firma_id);
create index if not exists idx_ihale_teklifleri_durum on public.ihale_teklifleri (durum);

-- ═══════════════════════════════════════════════════════════════════════════
-- 2) RLS
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.ihale_teklifleri enable row level security;

-- Teklif veren kendi tekliflerini görebilir
create policy "teklif_sahibi_read"
    on public.ihale_teklifleri for select
    using (auth.uid() = user_id);

-- İhale sahibi firma yöneticisi gelen teklifleri görebilir
create policy "ihale_sahibi_read"
    on public.ihale_teklifleri for select
    using (
        exists (
            select 1 from public.kurumsal_firma_yoneticileri
            where firma_id::text = ihale_teklifleri.firma_id
              and user_id = auth.uid()
        )
    );

-- Giriş yapmış kullanıcı teklif verebilir
create policy "authenticated_insert"
    on public.ihale_teklifleri for insert
    with check (auth.uid() = user_id);

-- Enes Doğanay | 13 Nisan 2026: Teklif veren kendi gönderilmiş/taslak teklifini güncelleyebilir
create policy "teklif_sahibi_update"
    on public.ihale_teklifleri for update
    using (auth.uid() = user_id and durum in ('taslak', 'gonderildi'))
    with check (auth.uid() = user_id);

-- İhale sahibi firma yöneticisi durum güncelleyebilir (kabul/red)
create policy "ihale_sahibi_status_update"
    on public.ihale_teklifleri for update
    using (
        exists (
            select 1 from public.kurumsal_firma_yoneticileri
            where firma_id::text = ihale_teklifleri.firma_id
              and user_id = auth.uid()
        )
    );

-- Enes Doğanay | 13 Nisan 2026: Teklif veren kendi gönderilmiş/taslak teklifini silebilir (geri çek)
create policy "teklif_sahibi_delete"
    on public.ihale_teklifleri for delete
    using (auth.uid() = user_id and durum in ('taslak', 'gonderildi'));
