-- Enes Doğanay | 13 Mayıs 2026: Yeni ihale e-posta uyarı abonelikleri
-- Kullanıcı belirli kategorilerde ihale açılınca bildirim almak isteyebilir

CREATE TABLE IF NOT EXISTS public.ihale_uyarilari (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    email       text NOT NULL,
    -- NULL = tüm ihaleler; doluysa yalnızca bu kategoride
    kategori    text,
    aktif       boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- Bir kullanıcı aynı kategori için tek abonelik tutabilir
CREATE UNIQUE INDEX IF NOT EXISTS ihale_uyarilari_unique
    ON public.ihale_uyarilari (user_id, COALESCE(kategori, ''));

CREATE INDEX IF NOT EXISTS idx_ihale_uyarilari_user
    ON public.ihale_uyarilari (user_id);

CREATE INDEX IF NOT EXISTS idx_ihale_uyarilari_kategori
    ON public.ihale_uyarilari (kategori) WHERE aktif = true;

ALTER TABLE public.ihale_uyarilari ENABLE ROW LEVEL SECURITY;

-- Kullanıcı sadece kendi aboneliklerini görebilir/yönetebilir
CREATE POLICY "Kendi aboneliklerini gör"
    ON public.ihale_uyarilari FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Kendi aboneliğini ekle"
    ON public.ihale_uyarilari FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Kendi aboneliğini güncelle"
    ON public.ihale_uyarilari FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Kendi aboneliğini sil"
    ON public.ihale_uyarilari FOR DELETE
    USING (auth.uid() = user_id);
