-- Enes Doğanay | 9 Mayıs 2026: Teklif revize geçmişi — teklifin her güncellemesinde önceki değerler kaydedilir
-- Supabase Dashboard > SQL Editor'de çalıştırın.

-- ═══════════════════════════════════════════════════════════════
-- 1) revize_sayisi kolonu (ihale_teklifleri tablosuna)
-- ═══════════════════════════════════════════════════════════════
ALTER TABLE public.ihale_teklifleri
    ADD COLUMN IF NOT EXISTS revize_sayisi integer NOT NULL DEFAULT 0;

-- ═══════════════════════════════════════════════════════════════
-- 2) Geçmiş tablosu
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS public.ihale_teklif_gecmisi (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teklif_id         bigint NOT NULL REFERENCES public.ihale_teklifleri(id) ON DELETE CASCADE,
    revize_no         integer NOT NULL,                     -- 1, 2, 3 ...
    kalemler          jsonb,
    toplam_tutar      numeric(15,2),
    para_birimi       text,
    kdv_dahil         boolean,
    teslim_suresi_gun integer,
    teslim_aciklamasi text,
    not_field         text,
    ek_dosya_url      text,
    ek_dosya_adi      text,
    olusturulma_tarihi timestamptz NOT NULL DEFAULT now()   -- bu revize ne zaman gönderilmişti
);

CREATE INDEX IF NOT EXISTS idx_teklif_gecmisi_teklif ON public.ihale_teklif_gecmisi (teklif_id);

-- ═══════════════════════════════════════════════════════════════
-- 3) RLS
-- ═══════════════════════════════════════════════════════════════
ALTER TABLE public.ihale_teklif_gecmisi ENABLE ROW LEVEL SECURITY;

-- İhale sahibi firma yöneticisi geçmişi görebilir
DROP POLICY IF EXISTS "ihale_sahibi_gecmis_read" ON public.ihale_teklif_gecmisi;
CREATE POLICY "ihale_sahibi_gecmis_read"
    ON public.ihale_teklif_gecmisi FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.ihale_teklifleri t
            JOIN public.kurumsal_firma_yoneticileri kfy ON kfy.firma_id = t.firma_id
            WHERE t.id = teklif_id AND kfy.user_id = auth.uid()
        )
    );

-- Teklif sahibi kendi geçmişini görebilir
DROP POLICY IF EXISTS "teklif_sahibi_gecmis_read" ON public.ihale_teklif_gecmisi;
CREATE POLICY "teklif_sahibi_gecmis_read"
    ON public.ihale_teklif_gecmisi FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.ihale_teklifleri t
            WHERE t.id = teklif_id AND t.user_id = auth.uid()
        )
    );

-- Teklif sahibi insert edebilir (revize kayıt)
DROP POLICY IF EXISTS "teklif_sahibi_gecmis_insert" ON public.ihale_teklif_gecmisi;
CREATE POLICY "teklif_sahibi_gecmis_insert"
    ON public.ihale_teklif_gecmisi FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.ihale_teklifleri t
            WHERE t.id = teklif_id AND t.user_id = auth.uid()
        )
    );
