-- Enes Doğanay | 6 Nisan 2026: Not hatirlaticilari ve profil bildirim merkezi icin gereken tablo/policy tanimlari

create extension if not exists pgcrypto;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.kullanici_hatirlaticilari (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  firma_id text not null,
  note_id text not null,
  note_title text,
  note_body text,
  reminder_at timestamptz not null,
  reminder_email text not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'cancelled', 'failed')),
  sent_at timestamptz,
  failed_at timestamptz,
  email_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_kullanici_hatirlaticilari_unique_pending_note
  on public.kullanici_hatirlaticilari (user_id, note_id)
  where status = 'pending';

create index if not exists idx_kullanici_hatirlaticilari_due
  on public.kullanici_hatirlaticilari (status, reminder_at);

create index if not exists idx_kullanici_hatirlaticilari_user_firma
  on public.kullanici_hatirlaticilari (user_id, firma_id);

create table if not exists public.bildirimler (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  type text not null default 'system',
  title text not null,
  message text not null,
  firma_id text,
  note_id text,
  reminder_id bigint,
  is_read boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_bildirimler_user_created_at
  on public.bildirimler (user_id, created_at desc);

create index if not exists idx_bildirimler_user_is_read
  on public.bildirimler (user_id, is_read);

drop trigger if exists set_kullanici_hatirlaticilari_updated_at on public.kullanici_hatirlaticilari;
create trigger set_kullanici_hatirlaticilari_updated_at
before update on public.kullanici_hatirlaticilari
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_bildirimler_updated_at on public.bildirimler;
create trigger set_bildirimler_updated_at
before update on public.bildirimler
for each row
execute function public.set_current_timestamp_updated_at();

alter table public.kullanici_hatirlaticilari enable row level security;
alter table public.bildirimler enable row level security;

drop policy if exists "Users can read own reminders" on public.kullanici_hatirlaticilari;
create policy "Users can read own reminders"
on public.kullanici_hatirlaticilari
for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own reminders" on public.kullanici_hatirlaticilari;
create policy "Users can insert own reminders"
on public.kullanici_hatirlaticilari
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own reminders" on public.kullanici_hatirlaticilari;
create policy "Users can update own reminders"
on public.kullanici_hatirlaticilari
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own reminders" on public.kullanici_hatirlaticilari;
create policy "Users can delete own reminders"
on public.kullanici_hatirlaticilari
for delete
using (auth.uid() = user_id);

drop policy if exists "Users can read own notifications" on public.bildirimler;
create policy "Users can read own notifications"
on public.bildirimler
for select
using (auth.uid() = user_id);

drop policy if exists "Users can update own notifications" on public.bildirimler;
create policy "Users can update own notifications"
on public.bildirimler
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);