-- Enes Doğanay | 7 Nisan 2026: Teklif talepleri ve mesajlaşma sistemi
-- Bireysel→Kurumsal, Kurumsal→Kurumsal teklif akışı + in-app chat + bildirimler

-- ═══════════════════════════════════════════════════════════════════════════
-- 1) TEKLİF TALEPLERİ
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.teklif_talepleri (
  id bigint generated by default as identity primary key,
  firma_id text not null,                  -- teklif ALAN firma
  user_id uuid not null,                   -- gönderen kullanıcı (her zaman mevcut)
  gonderen_firma_id text,                  -- eğer gönderen de kurumsal ise, onun firma_id'si
  ad_soyad text not null,
  email text not null,
  telefon text,
  firma_adi text,                          -- gönderenin firma adı (varsa)
  konu text not null,
  mesaj text not null,
  miktar text,
  teslim_tarihi text,
  durum text not null default 'pending' check (durum in ('pending', 'read', 'replied', 'rejected', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_teklif_talepleri_updated_at on public.teklif_talepleri;
create trigger set_teklif_talepleri_updated_at
  before update on public.teklif_talepleri
  for each row
  execute function public.set_current_timestamp_updated_at();

create index if not exists idx_teklif_talepleri_firma on public.teklif_talepleri (firma_id);
create index if not exists idx_teklif_talepleri_user on public.teklif_talepleri (user_id);
create index if not exists idx_teklif_talepleri_gonderen_firma on public.teklif_talepleri (gonderen_firma_id);
create index if not exists idx_teklif_talepleri_durum on public.teklif_talepleri (durum);

alter table public.teklif_talepleri enable row level security;

-- Gönderen kendi tekliflerini görebilir
create policy "Kullanici kendi tekliflerini gorebilir"
  on public.teklif_talepleri for select
  using (auth.uid() = user_id);

-- Gönderen teklif oluşturabilir
create policy "Kullanici teklif olusturabilir"
  on public.teklif_talepleri for insert
  with check (auth.uid() = user_id);

-- Firma yöneticisi kendi firmasına gelen teklifleri görebilir
create policy "Firma yoneticisi gelen teklifleri gorebilir"
  on public.teklif_talepleri for select
  using (
    exists (
      select 1 from public.kurumsal_firma_yoneticileri kfy
      where kfy.user_id = auth.uid()
        and kfy.firma_id::text = teklif_talepleri.firma_id::text
    )
  );

-- Firma yöneticisi kendi firmasından GÖNDERİLEN teklifleri görebilir
create policy "Firma yoneticisi giden teklifleri gorebilir"
  on public.teklif_talepleri for select
  using (
    exists (
      select 1 from public.kurumsal_firma_yoneticileri kfy
      where kfy.user_id = auth.uid()
        and kfy.firma_id::text = teklif_talepleri.gonderen_firma_id::text
    )
  );

-- Firma yöneticisi teklif durumunu güncelleyebilir
create policy "Firma yoneticisi teklif durumunu guncelleyebilir"
  on public.teklif_talepleri for update
  using (
    exists (
      select 1 from public.kurumsal_firma_yoneticileri kfy
      where kfy.user_id = auth.uid()
        and kfy.firma_id::text = teklif_talepleri.firma_id::text
    )
  );

-- ═══════════════════════════════════════════════════════════════════════════
-- 2) TEKLİF MESAJLARI (Chat)
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.teklif_mesajlari (
  id bigint generated by default as identity primary key,
  teklif_id bigint not null references public.teklif_talepleri (id) on delete cascade,
  sender_id uuid not null,
  sender_role text not null default 'user' check (sender_role in ('user', 'company')),
  mesaj text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_teklif_mesajlari_teklif on public.teklif_mesajlari (teklif_id);
create index if not exists idx_teklif_mesajlari_sender on public.teklif_mesajlari (sender_id);

alter table public.teklif_mesajlari enable row level security;

-- Gönderen kendi teklifinin mesajlarını görebilir
create policy "Teklif sahibi mesajlari gorebilir"
  on public.teklif_mesajlari for select
  using (
    exists (
      select 1 from public.teklif_talepleri tt
      where tt.id = teklif_mesajlari.teklif_id
        and tt.user_id = auth.uid()
    )
  );

-- Firma yöneticisi firmasına gelen teklif mesajlarını görebilir
create policy "Firma yoneticisi teklif mesajlarini gorebilir"
  on public.teklif_mesajlari for select
  using (
    exists (
      select 1 from public.teklif_talepleri tt
      join public.kurumsal_firma_yoneticileri kfy on kfy.firma_id::text = tt.firma_id::text
      where tt.id = teklif_mesajlari.teklif_id
        and kfy.user_id = auth.uid()
    )
  );

-- Gönderen kendi teklifine mesaj yazabilir
create policy "Teklif sahibi mesaj yazabilir"
  on public.teklif_mesajlari for insert
  with check (
    auth.uid() = sender_id
    and exists (
      select 1 from public.teklif_talepleri tt
      where tt.id = teklif_mesajlari.teklif_id
        and tt.user_id = auth.uid()
    )
  );

-- Firma yöneticisi mesaj yazabilir
create policy "Firma yoneticisi mesaj yazabilir"
  on public.teklif_mesajlari for insert
  with check (
    auth.uid() = sender_id
    and exists (
      select 1 from public.teklif_talepleri tt
      join public.kurumsal_firma_yoneticileri kfy on kfy.firma_id::text = tt.firma_id::text
      where tt.id = teklif_mesajlari.teklif_id
        and kfy.user_id = auth.uid()
    )
  );

-- ═══════════════════════════════════════════════════════════════════════════
-- 3) BİLDİRİM TETİKLEYİCİLERİ
-- ═══════════════════════════════════════════════════════════════════════════

-- Yeni teklif geldiğinde firma yöneticisine bildirim at
create or replace function public.fn_teklif_bildirim_olustur()
returns trigger
language plpgsql
security definer
as $$
declare
  yonetici_row record;
  firma_adi_val text;
begin
  -- Firma adını bul
  select firma_adi into firma_adi_val from public.firmalar where "firmaID"::text = new.firma_id::text limit 1;

  -- Firma yöneticilerine bildirim gönder
  for yonetici_row in
    select user_id from public.kurumsal_firma_yoneticileri where firma_id::text = new.firma_id::text
  loop
    insert into public.bildirimler (user_id, type, title, message, firma_id, metadata)
    values (
      yonetici_row.user_id,
      'quote_received',
      'Yeni Teklif Talebi',
      new.ad_soyad || ' size "' || new.konu || '" konulu bir teklif talebi gönderdi.',
      new.firma_id::text,
      jsonb_build_object('teklif_id', new.id, 'gonderen_ad', new.ad_soyad)
    );
  end loop;

  return new;
end;
$$;

drop trigger if exists trg_teklif_bildirim on public.teklif_talepleri;
create trigger trg_teklif_bildirim
  after insert on public.teklif_talepleri
  for each row
  execute function public.fn_teklif_bildirim_olustur();

-- Teklif mesajı geldiğinde karşı tarafa bildirim at
create or replace function public.fn_teklif_mesaj_bildirim()
returns trigger
language plpgsql
security definer
as $$
declare
  teklif_row record;
  hedef_user_id uuid;
  sender_name text;
begin
  select * into teklif_row from public.teklif_talepleri where id = new.teklif_id;

  if new.sender_role = 'company' then
    -- Firma yanıt verdi → talep gönderene bildirim
    hedef_user_id := teklif_row.user_id;
    select firma_adi into sender_name from public.firmalar where "firmaID"::text = teklif_row.firma_id::text limit 1;
    sender_name := coalesce(sender_name, 'Firma');

    insert into public.bildirimler (user_id, type, title, message, firma_id, metadata)
    values (
      hedef_user_id,
      'quote_reply',
      'Teklif Talebinize Yanıt Geldi',
      sender_name || ' "' || teklif_row.konu || '" konulu talebinize yanıt verdi.',
      teklif_row.firma_id::text,
      jsonb_build_object('teklif_id', teklif_row.id)
    );
  else
    -- Kullanıcı mesaj yazdı → firma yöneticisine bildirim
    for hedef_user_id in
      select user_id from public.kurumsal_firma_yoneticileri where firma_id::text = teklif_row.firma_id::text
    loop
      insert into public.bildirimler (user_id, type, title, message, firma_id, metadata)
      values (
        hedef_user_id,
        'quote_message',
        'Teklif Talebinde Yeni Mesaj',
        teklif_row.ad_soyad || ' "' || teklif_row.konu || '" konulu talepte mesaj gönderdi.',
        teklif_row.firma_id::text,
        jsonb_build_object('teklif_id', teklif_row.id)
      );
    end loop;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_teklif_mesaj_bildirim on public.teklif_mesajlari;
create trigger trg_teklif_mesaj_bildirim
  after insert on public.teklif_mesajlari
  for each row
  execute function public.fn_teklif_mesaj_bildirim();
