-- Enes Doğanay | 6 Nisan 2026: Dinamik ihaleler sayfasi ve firma detay ihale akisi icin temel tablo tanimi

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.firma_ihaleleri (
  id bigint generated by default as identity primary key,
  firma_id text not null,
  slug text unique,
  baslik text not null,
  aciklama text not null,
  ihale_tipi text,
  kategori text,
  il_ilce text,
  referans_no text,
  yayin_tarihi timestamptz not null default now(),
  son_basvuru_tarihi timestamptz not null,
  durum text not null default 'active' check (durum in ('draft', 'active', 'cancelled', 'completed', 'closed')),
  butce_notu text,
  basvuru_email text,
  iletisim_telefon text,
  dokuman_url text,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_firma_ihaleleri_firma_id on public.firma_ihaleleri (firma_id);
create index if not exists idx_firma_ihaleleri_deadline on public.firma_ihaleleri (son_basvuru_tarihi);
create index if not exists idx_firma_ihaleleri_status on public.firma_ihaleleri (durum, is_active);

drop trigger if exists set_firma_ihaleleri_updated_at on public.firma_ihaleleri;
create trigger set_firma_ihaleleri_updated_at
before update on public.firma_ihaleleri
for each row
execute function public.set_current_timestamp_updated_at();

alter table public.firma_ihaleleri enable row level security;

drop policy if exists "Public can read published tenders" on public.firma_ihaleleri;
create policy "Public can read published tenders"
on public.firma_ihaleleri
for select
using (durum <> 'draft');

-- Enes Doğanay | 6 Nisan 2026: Ilk test verisi eklemek isterseniz asagidaki ornegi kendi firma_id'nize gore uyarlayin
-- insert into public.firma_ihaleleri (firma_id, slug, baslik, aciklama, ihale_tipi, kategori, il_ilce, referans_no, yayin_tarihi, son_basvuru_tarihi, butce_notu, basvuru_email, is_featured)
-- values ('FIRMA_ID', 'ornek-ihale', 'Örnek İhale', 'Bu kayıt test amaçlıdır.', 'Alım', 'Makine', 'İstanbul / Tuzla', 'TED-2026-001', now(), now() + interval '7 day', '500.000 - 750.000 TL', 'teklif@firma.com', true);